# Generated by Django 4.0.5 on 2022-06-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiProducto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_costo',
            field=models.IntegerField(default=0),
        ),
    ]
