# Generated by Django 4.0.5 on 2022-06-29 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiProducto', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='rut',
        ),
    ]
