# Generated by Django 4.0.5 on 2022-06-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiProducto', '0005_profilefeeditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilefeeditem',
            name='status_text',
            field=models.CharField(max_length=255),
        ),
    ]
