# Generated by Django 4.0.5 on 2022-06-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_marca_tipo_usuario_alter_producto_options_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_costo',
            field=models.IntegerField(default=0),
        ),
    ]
