# Generated by Django 4.0.5 on 2022-06-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_detalleventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='direccion_despacho',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
