# Generated by Django 4.0.5 on 2022-06-29 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_venta_direccion_despacho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_usuario',
        ),
        migrations.DeleteModel(
            name='Tipo_usuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
