# Generated by Django 4.0.5 on 2022-06-30 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_donacion_detalledonacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donacion',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='detalledonacion',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detalledonacion',
            name='id_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.usuario'),
        ),
        migrations.AddField(
            model_name='tipo_usuario',
            name='descuento',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='productos.tipo_usuario'),
        ),
    ]
