# Generated by Django 4.0.5 on 2022-06-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_remove_donacion_id_usuario_detalledonacion_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
