# Generated by Django 4.0.5 on 2022-06-30 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_alter_venta_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='venta',
            name='estado_despacho',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.despacho'),
        ),
    ]
