# Generated by Django 4.0.6 on 2022-07-10 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_despacho_venta_estado_despacho'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='venta',
            name='notas',
            field=models.TextField(default=1, max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='medio_pago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.mediopago'),
            preserve_default=False,
        ),
    ]
